version: '2'
services:
    erpclic-app:
        image: erpclic
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://erpclic-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=erpclic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://erpclic-elasticsearch:9200
        ports:
            - 8080:8080
    erpclic-mongodb:
        extends:
            file: mongodb.yml
            service: erpclic-mongodb
    erpclic-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: erpclic-elasticsearch
